// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package db

import (
	"context"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (
    created_at, updated_at, url, interval_seconds
) VALUES (
    datetime('now'), datetime('now'), ?, ?
)
RETURNING id, created_at, updated_at, url, interval_seconds
`

type CreateLinkParams struct {
	Url             string
	IntervalSeconds int64
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, createLink, arg.Url, arg.IntervalSeconds)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.IntervalSeconds,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :one
DELETE FROM links
WHERE id = ?
RETURNING id, created_at, updated_at, url, interval_seconds
`

func (q *Queries) DeleteLink(ctx context.Context, id int64) (Link, error) {
	row := q.db.QueryRowContext(ctx, deleteLink, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.IntervalSeconds,
	)
	return i, err
}

const deleteLinkFromURL = `-- name: DeleteLinkFromURL :one
DELETE FROM links
WHERE url = ?
RETURNING id, created_at, updated_at, url, interval_seconds
`

func (q *Queries) DeleteLinkFromURL(ctx context.Context, url string) (Link, error) {
	row := q.db.QueryRowContext(ctx, deleteLinkFromURL, url)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.IntervalSeconds,
	)
	return i, err
}

const getLink = `-- name: GetLink :one
SELECT id, created_at, updated_at, url, interval_seconds FROM links
WHERE id = ?
`

func (q *Queries) GetLink(ctx context.Context, id int64) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLink, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.IntervalSeconds,
	)
	return i, err
}

const getLinkFromURL = `-- name: GetLinkFromURL :one
SELECT id, created_at, updated_at, url, interval_seconds FROM links
WHERE url = ?
`

func (q *Queries) GetLinkFromURL(ctx context.Context, url string) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLinkFromURL, url)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.IntervalSeconds,
	)
	return i, err
}

const listLinks = `-- name: ListLinks :many
SELECT id, created_at, updated_at, url, interval_seconds FROM links
ORDER BY updated_at DESC
`

func (q *Queries) ListLinks(ctx context.Context) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, listLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Url,
			&i.IntervalSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
    SET updated_at = datetime('now'),
    interval_seconds = ?
WHERE id = ?
RETURNING id, created_at, updated_at, url, interval_seconds
`

type UpdateLinkParams struct {
	IntervalSeconds int64
	ID              int64
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, updateLink, arg.IntervalSeconds, arg.ID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.IntervalSeconds,
	)
	return i, err
}

const updateLinkFromURL = `-- name: UpdateLinkFromURL :one
UPDATE links
    SET updated_at = datetime('now'),
    interval_seconds = ?
WHERE url = ?
RETURNING id, created_at, updated_at, url, interval_seconds
`

type UpdateLinkFromURLParams struct {
	IntervalSeconds int64
	Url             string
}

func (q *Queries) UpdateLinkFromURL(ctx context.Context, arg UpdateLinkFromURLParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, updateLinkFromURL, arg.IntervalSeconds, arg.Url)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.IntervalSeconds,
	)
	return i, err
}
