// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Link struct {
	ID              int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Url             string
	IntervalSeconds int64
}
